version: '3'
services:
  fastdfs:
    build: .
    image: qbanxiaoli/fastdfs
    # 该容器是否需要开机启动+自动重启。若需要，则取消注释。
    restart: always
    container_name: fastdfs
    environment:
      # nginx服务端口,默认80端口，可修改
      WEB_PORT: 80
      # tracker_server服务端口，默认22122端口，可修改
      FDFS_PORT: 22122
      # storage_server服务端口，默认23000端口，可修改
      STORAGE_PORT: 23000
      # fastdht服务端口，默认11411端口，可修改
      FDHT_PORT: 11411
      # docker所在的宿主机内网地址，默认使用eth0网卡的地址
      IP: 192.168.0.105
      # 防盗链配置
      # 是否做token检查，缺省值为false
      CHECK_TOKEN: 0
      # 生成token的有效时长，默认900s
      TOKEN_TTL: 900
      # 生成token的密钥
      SECRET_KEY: FastDFS1234567890
      # token检查失败，返回的本地文件内容，可以通过文件挂载的方式进行修改
      TOKEN_CHECK_FAIL: /etc/fdfs/anti-steal.jpg
    volumes:
      # 将本地目录映射到docker容器内的fastdfs数据存储目录，将fastdfs文件存储到主机上，以免每次重建docker容器，之前存储的文件就丢失了。
      - ～/fastdfs:/var/local
    # 网络模式为host，可不暴露端口，即直接使用宿主机的网络端口，只适用于linux系统
    network_mode: host